{
  "log": { "level": "info" },
  "dns": { "servers": [{ "address": "tls://8.8.8.8" }] },
  "inbounds":
    [
      {
        "type": "vless",
        "tag": "VLESSReality",
        "listen": "::",
        "listen_port": 443,
        "users":
          [{ "name": "$NAME", "uuid": "$UUID", "flow": "xtls-rprx-vision" }],
        "tls":
          {
            "enabled": true,
            "server_name": "$SNI",
            "reality":
              {
                "enabled": true,
                "handshake": { "server": "$SNI", "server_port": 443 },
                "private_key": "$PRIVATE_KEY",
                "short_id": "$SHORT_ID",
              },
          },
      },
    ],
  "outbounds": [{ "type": "direct" }],
}
